apiVersion: v1
kind: Service
metadata:
  name: device-report-service
  namespace: iot-learn
  labels:
    app: device-report-service
spec:
  type: ClusterIP
  selector:
    app: device-report-service
  ports:
    - name: http
      port: 8765
      targetPort: 8765