{{- if and .Values.deviceReport.enabled .Values.deviceReport.rollouts.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ .Values.deviceReport.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "iot-learn-lab.labels" . | nindent 4 }}
    app: {{ .Values.deviceReport.name }}
spec:
  replicas: {{ .Values.deviceReport.replicaCount }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: {{ .Values.deviceReport.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.deviceReport.name }}
        version: {{ .Values.deviceReport.versionLabel | quote }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/device-report-configmap.yaml") . | sha256sum }}
    spec:
      containers:
        - name: {{ .Values.deviceReport.name }}
          image: {{ .Values.deviceReport.image | quote }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.deviceReport.port }}
              name: http
          envFrom:
            - configMapRef:
                name: device-report-middleware
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: {{ .Values.deviceReport.port }}
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: {{ .Values.deviceReport.port }}
            initialDelaySeconds: 60
            periodSeconds: 20
          resources:
            {{- toYaml .Values.deviceReport.resources | nindent 12 }}
  strategy:
    canary:
      steps:
        {{- toYaml .Values.deviceReport.rollouts.steps | nindent 8 }}
{{- end }}
