# 叠加：helm upgrade ... -f values.yaml -f values-v1.yaml
deviceReport:
  versionLabel: v1
  image: device-report-service:0.1.0-SNAPSHOT
commandDispatch:
  versionLabel: v1
deviceReportConsumer:
  versionLabel: v1