deviceReport:
  versionLabel: v1
  appVersion: v1-canary-drill
  canaryBugEnabled: false
  replicaCount: 5
  image: device-report-service:0.1.0-SNAPSHOT
  rollouts:
    enabled: true
commandDispatch:
  versionLabel: v1
deviceReportConsumer:
  versionLabel: v1