apiVersion: v1
kind: ConfigMap
metadata:
  name: device-report-consumer-middleware
  namespace: iot-learn
data:
  DB_HOST: "host.minikube.internal"
  DB_PORT: "5432"
  DB_USERNAME: "postgres"
  DB_PASSWORD: "postgres"
  NACOS_ADDR: "192.168.19.64:8848"
  SPRING_PROFILES_ACTIVE: "k8s"
  KAFKA_BOOTSTRAP: "host.minikube.internal:9092"
  KAFKA_TOPIC: "device-report-events"
  KAFKA_CONSUMER_GROUP_ID: "device-report-consumer-group-k8s"